var worldConf = {
  backgroundColHSB: {h: 0, s: 0, b: 62, a: 100},
  deciduousForest: {
    treeSize: 35,
    xVariance: 0.25,
    xIncrement: 0.5,
    yVariance: 0.6,
    yIncrement: 0.6,
    xOffsetVarianceMin: -0.2,
    xOffsetVarianceMax: 0.125,
    yOffsetVarianceMin: -0.1,
    yOffsetVarianceMax: 0.2,
  },
  deciduousTree: {
    stemLengthMean: 3,
    stemLengthDeviation: 0,
    stemAngleDeviation: 0,
    stemThicknessFraction: 8,
    stemFillColHSB: {h: 40, s: 91, b: 21, a: 0},
    stemStrokeColHSB: {h: 40, s: 91, b: 21, a: 100},
    stemStrokeWeight: 4,
    nodeDistanceDeviationMin: 10,
    nodeDistanceDeviationMax: 50,
    foilageAngleVariance: Math.PI / 16,
    foilagHueDeviation: 20,
    foilageFluffyness: 1.6,
    foilageFluffynessVariance: 0.2,
    foilageMidpoint: 0.5,
    foilageMidpointVariance: 0.1,
    foilageFillColHSB: {h: 121, s: 36, b: 35, a: 100},
    foilageStrokeColHSB: {h: 121, s: 26, b: 0, a: 100},
    foilageStrokeWeight: 0.5,
  },
  evergreenForest: {
    treeSize: 35,
    xVariance: 0.25,
    xIncrement: 0.4,
    yVariance: 0.33,
    yIncrement: 0.7,
    xOffsetVarianceMin: -0.2,
    xOffsetVarianceMax: 0.125,
    yOffsetVarianceMin: -0.1,
    yOffsetVarianceMax: 0.2,
  },
  evergreenTree: {
    stemLengthDeviation: 0,
    stemAngleDeviation: 0,
    stemThicknessFraction: 10,
    stemSegmentShortening: 0.75,
    stemSegmentThinning: 0.8,
    stemFillColHSB: {h: 40, s: 91, b: 21, a: 0},
    stemStrokeColHSB: {h: 40, s: 91, b: 21, a: 100},
    stemStrokeWeight: 4,
    foilagHueDeviation: 20,
    foilageCoverage: 1.5,
    foilageCoverageDeviation: 0.15,
    foilageHeight: 0.75,
    foilageHeightDeviation: 0.1,
    foilageFluffyness: 0.7,
    foilageFluffynessVariance: 0.1,
    foilageMidpoint: 0.5,
    foilageMidpointVariance: 0.3,
    foilageFillColHSB: {h: 121, s: 36, b: 31, a: 100},
    foilageStrokeColHSB: {h: 121, s: 26, b: 0, a: 100},
    foilageStrokeWeight: 0.5,
  },
  city: {
    houseWidthMin: 12,
    houseWidthMax: 30,
  },
  house: {
    wallStrokeColHSB: {h: 0, s: 0, b: 0, a: 100},
    wallStrokeWeight: 1,
    wallFillColHSB: {h: 33, s: 20, b: 78, a: 100},
    windowStrokeColHSB: {h: 0, s: 0, b: 0, a: 100},
    windowStrokeWeight: 0.0,
    windowFillColHSB: {h: 27, s: 71, b: 25, a: 100},
    roofStrokeColHSB: {h: 0, s: 0, b: 0, a: 100},
    roofStrokeWeight: 1,
    roofFillColHSB: {h: 355, s: 97, b: 60, a: 100},
    windowMinWidth: 2,
    windowMaxWidth: 4,
    windowMinHeight: 4,
    windowMaxHeight: 10,
    windowMinGapX: 2,
    windowMaxGapX: 4,
    windowMinGapY: 3,
    windowMaxGapY: 5,
    roofOverhangMean: 0.16,
    roofOverhangDeviation: 0.05,
    roofHeightMean: 0.35,
    roofHeightDeviation: 0.05,
    roofCurvatureMean: 1,
    roofCurvatureDeviation: 0.8,
    roofCurvatureMidpointMean: 0.5,
    roofCurvatureMidpointDeviation: 0,
  },
  mountainRange: {
    minSizeX: 30,
    maxSizeX: 70,
    minSizeY: 25,
    maxSizeY: 40,
    varianceY: 0.6,
    xScaleFactor: 1.7,
    yScaleFactor: 1.1,
    xIncrement: 1.5,
    yIncrement: 0.3,
  },
  mountain: {
    midpointIterations: 2,
    pointVariance: 0.1,
    shadowStrokeWeight: 0,
    shadowFillCol: {h: 27, s: 15, b: 50, a: 100},
    ridgeStrokeCol: {h: 0, s: 0, b: 0, a: 100},
    ridgeStrokeWeight: 1,
    ridgeMPVarianceX: 0.1,
    ridgeMPVarianceY: 0.005,
    ridgeMPAmplitude: 0.08,
    ridgeMPAmplitudeDampening: 0.7,
    shadowMPVarianceX: 0.05,
    shadowMPVarianceY: 0.005,
    shadowMPAmplitude: 0.08,
    shadowMPAmplitudeDampening: 0.7,
    areaMPVarianceX: 0.08,
    areaMPVarianceY: 0.005,
    areaMPAmplitude: 0.08,
    areaMPAmplitudeDampening: 0.7,
  },
  swamp: {
    strokeColHSB: {h: 212, s: 66, b: 60, a: 100},
    strokeWeight: 2,
    xVariance: 5,
    lengthMin: 20,
    lengthMax: 50,
    gapLength: 10,
    lineGap: 10,
  },
  lake: {
    strokeColHSB: {h: 212, s: 66, b: 60, a: 100},
    strokeWeight: 2,
    fillColHSB: {h: 212, s: 57, b: 80, a: 100},
    midpoint: 0.4,
    midpointVariance: 0.1,
  }
};
